import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

const TOOLS_DIR = join(import.meta.dir, "..", "src", "tools");
const OUT_FILE = join(TOOLS_DIR, "reset-css.generated.ts");

function resolveImports(cssPath: string): string {
  const css = readFileSync(cssPath, "utf8");
  return css.replace(/^@import\s+"(.+?)";$/gm, (_m, relPath) =>
    resolveImports(join(dirname(cssPath), relPath)),
  );
}

function toExport(name: string, cssFile: string): string {
  const css = resolveImports(join(TOOLS_DIR, cssFile));
  return `export const ${name} = ${JSON.stringify(css)};\n`;
}

const header = `// Generated by scripts/generate-reset.ts — do not edit directly.\n// Source: src/tools/{reset,design}.css\n\n`;

const body =
  toExport("RESET", "reset.css") + toExport("COMPONENTS", "design.css");

writeFileSync(OUT_FILE, header + body);
console.log(`generated ${OUT_FILE}`);
